version: ${project.version}
main: me.rockyhawk.commandpanels.CommandPanels
name: ${project.name}
author: RockyHawk
api-version: '1.13'
description: ${project.description}
softdepend: [PlaceholderAPI, Vault, HeadDatabase, TokenManager, VotingPlugin, MMOItems, CustomItems, ChestSort, CoinsAPINB]
permissions:
   commandpanel.panel.default:
      default: true
   commandpanel.other:
      default: op
   commandpanel.panel.*:
      default: op
   commandpanel.item.*:
      default: op
   commandpanel.reload:
      default: op
   commandpanel.debug:
      default: op
   commandpanel.block.add:
      default: op
   commandpanel.block.remove:
      default: op
   commandpanel.block.list:
      default: op
   commandpanel.generate:
      default: op
   commandpanel.version:
      default: true
   commandpanel.update:
      default: op
   commandpanel.data:
      default: op
   commandpanel.edit:
      default: op
   commandpanel.list:
      default: op
   commandpanel.import:
      default: op
libraries:
   - org.asynchttpclient:async-http-client:${asynchttp.version}